---
 func: 'calcGDR'
 input_group_info: 'C:/Users/norab/Master/WillowProject/Willow1.0/Data/phydist_population_classes.tsv'
 input_phydist_folder: 'C:/Users/norab/Master/thesis_data/test_input_data/phydists_10samples/'
 output_folder: 'C:/Users/norab/Master/WillowProject/Willow1.0/jobs/test_GDR_10genes/'
 output_unprocessed: 'test_GDR_10genes_unprocessed_files_datetime.csv'
 group_categories: 'SUPER___SUB'
 num_random_values: 0
 filter_skip: 'None'
 filter_select: 'None'