---
title: "GDRsimulationStats"
author: "Nora Bull"
date: "2 1 2022"
output: html_document
---


# Willow statistics simulation


# Function to calculate and save p-values for simulated GDR
```{r}

GDRsim_pval_calcSave <- function(GDRnull_file, pvalSaveFile) {
  
  "
  Input:
    GDRnull_file: path to file with random GDR values 
      Format: CSV
      
    pval_save_file: desired filepath to store values
      Format: CSV
  "
  
  # Read data
  GDRnull_data <- read.csv(GDRnull_file)
  col = colnames(GDRnull_data)
  data = unlist(strsplit(col, '_'))
  G = gsub("G", "", data[1])
  perm = gsub("P", "", data[2])
  GDR = as.double(gsub("GDR", "", data[3]))
  uniq_pvals = length(unique(GDRnull_data[,1]))
  
  # Create empirical cumulative distribution function (ecdf)
  P = ecdf(GDRnull_data[,1])
  
  # Calculate p value for GDR
  p_val = P(GDR)

  # Save p val to file
  #GDR <- as.character(GDR)
  cat(c(G, perm, GDR, uniq_pvals, p_val), file = pvalSaveFile, sep = ",", append = TRUE)
  cat('\n', file = pvalSaveFile, append=TRUE)
}

```


# Run p-value calculation
```{r}
# Create file to save p-values:
save_file <- "C:/Users/norab/Master/thesis_data/simulation/simNull_pvals_24.11.21.csv"
file.create(save_file)

cat(c("group_size,permutations,GDR,n_uniq_pvals,pval\n"), file = save_file, append=TRUE)

# Create list of files to process (each containing random GDRs for one simulated GDR values)
simNull_files <- list.files(path="C:/Users/norab/Master/thesis_data/simulation/simData/", full.names=TRUE, recursive=FALSE)

# Apply GDRsim_pval_calcSave function to all simNull_files
run <- sapply(simNull_files, GDRsim_pval_calcSave, save_file) 
```


# Multiple testing correction
```{r}
# Read data
all_data <- read.csv(save_file, sep=",")

# adjust
all_data$pval_adj_holm <- p.adjust(all_data$pval)
all_data$pval_adj_bonferroni <- p.adjust(all_data$pval, method = "bonferroni")
all_data$hommel <- p.adjust(all_data$pval, method = "hommel")

# Save
save_to <- 'C:/Users/norab/Master/thesis_data/simulation/simNull_alldata_24.11.21.csv'
write.csv(all_data, save_to, row.names = FALSE)
```
