---
 func: 'calcNullSDR'
 num_rand_trees: 100
 input_files: '/mnt/data21/nora/data/job_input/cophenetic_dists_47genes/'
 input_pop_info: '/mnt/data21/nora/data/job_input/phydist_population_classes.tsv'
 input_config_folder: '/mnt/data21/nora/data/configs/'
 log_config: 'logging.ini'
 output_folder: '/mnt/data21/nora/data/job_output/'
 output_log: 'log_SDRnullDist_47genes_datetime.log'
 output_SDRsuper: 'nullDistSDRsuper_47genes_datetime.csv'
 output_SDRsub: 'nullDistSDRsub_47genes_datetime.csv'
 output_unprocessed: 'unprocessed_files_nullDistSDRcalc_47genes_datetime.csv'
 LOGGER_SECTION: 'Logger'